//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotationsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESTA.Resources.DataAnnotationsResource", typeof(DataAnnotationsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Qualification.
        /// </summary>
        public static string academicqualification {
            get {
                return ResourceManager.GetString("academicqualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Certificate.
        /// </summary>
        public static string academicqualificationImg {
            get {
                return ResourceManager.GetString("academicqualificationImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address in Arabic.
        /// </summary>
        public static string addressar {
            get {
                return ResourceManager.GetString("addressar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address in English.
        /// </summary>
        public static string addressen {
            get {
                return ResourceManager.GetString("addressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Amount.
        /// </summary>
        public static string authamount {
            get {
                return ResourceManager.GetString("authamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography in Arabic.
        /// </summary>
        public static string bioar {
            get {
                return ResourceManager.GetString("bioar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography in English.
        /// </summary>
        public static string bioen {
            get {
                return ResourceManager.GetString("bioen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string birth {
            get {
                return ResourceManager.GetString("birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Number.
        /// </summary>
        public static string blockno {
            get {
                return ResourceManager.GetString("blockno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name in Arabic.
        /// </summary>
        public static string branchar {
            get {
                return ResourceManager.GetString("branchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name in English.
        /// </summary>
        public static string branchen {
            get {
                return ResourceManager.GetString("branchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured Amount.
        /// </summary>
        public static string capamount {
            get {
                return ResourceManager.GetString("capamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        public static string cardtype {
            get {
                return ResourceManager.GetString("cardtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string cdate {
            get {
                return ResourceManager.GetString("cdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmpassword {
            get {
                return ResourceManager.GetString("confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match .
        /// </summary>
        public static string confirmpassworderr {
            get {
                return ResourceManager.GetString("confirmpassworderr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string curr {
            get {
                return ResourceManager.GetString("curr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string currentpassword {
            get {
                return ResourceManager.GetString("currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in Arabic.
        /// </summary>
        public static string descar {
            get {
                return ResourceManager.GetString("descar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in English.
        /// </summary>
        public static string descen {
            get {
                return ResourceManager.GetString("descen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Address Is not Valid.
        /// </summary>
        public static string emailerr {
            get {
                return ResourceManager.GetString("emailerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported Email Format.
        /// </summary>
        public static string emailformaterr {
            get {
                return ResourceManager.GetString("emailformaterr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Reading Level.
        /// </summary>
        public static string englishrl {
            get {
                return ResourceManager.GetString("englishrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English WritingLevel.
        /// </summary>
        public static string englishwl {
            get {
                return ResourceManager.GetString("englishwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Number.
        /// </summary>
        public static string flatno {
            get {
                return ResourceManager.GetString("flatno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string floor {
            get {
                return ResourceManager.GetString("floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Grade.
        /// </summary>
        public static string fngrade {
            get {
                return ResourceManager.GetString("fngrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Description.
        /// </summary>
        public static string forumdesc {
            get {
                return ResourceManager.GetString("forumdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Level.
        /// </summary>
        public static string forumlevel {
            get {
                return ResourceManager.GetString("forumlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Title.
        /// </summary>
        public static string forumtitle {
            get {
                return ResourceManager.GetString("forumtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name In English.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name In Arabic.
        /// </summary>
        public static string fullnamear {
            get {
                return ResourceManager.GetString("fullnamear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradution Year.
        /// </summary>
        public static string gradutionyear {
            get {
                return ResourceManager.GetString("gradutionyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have You Read ?.
        /// </summary>
        public static string haveread {
            get {
                return ResourceManager.GetString("haveread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postgraduate degree.
        /// </summary>
        public static string highstudies {
            get {
                return ResourceManager.GetString("highstudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string homephone {
            get {
                return ResourceManager.GetString("homephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown.
        /// </summary>
        public static string hometown {
            get {
                return ResourceManager.GetString("hometown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Card Id.
        /// </summary>
        public static string idno {
            get {
                return ResourceManager.GetString("idno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job In Arabic.
        /// </summary>
        public static string jobar {
            get {
                return ResourceManager.GetString("jobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job in English.
        /// </summary>
        public static string joben {
            get {
                return ResourceManager.GetString("joben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        public static string lastdate {
            get {
                return ResourceManager.GetString("lastdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name.
        /// </summary>
        public static string levelname {
            get {
                return ResourceManager.GetString("levelname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Applicants should be between 10 - 9999.
        /// </summary>
        public static string maxallowedmemberserr {
            get {
                return ResourceManager.GetString("maxallowedmemberserr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum people who can apply.
        /// </summary>
        public static string maxcoursemembers {
            get {
                return ResourceManager.GetString("maxcoursemembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging Address.
        /// </summary>
        public static string meassagingaddress {
            get {
                return ResourceManager.GetString("meassagingaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mempership Expiry Month.
        /// </summary>
        public static string memexpiry {
            get {
                return ResourceManager.GetString("memexpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mempership Fee.
        /// </summary>
        public static string memfee {
            get {
                return ResourceManager.GetString("memfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mempership Expiry Month Should be between 1 and 12.
        /// </summary>
        public static string memmonthexpiryerr {
            get {
                return ResourceManager.GetString("memmonthexpiryerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in Arabic.
        /// </summary>
        public static string namear {
            get {
                return ResourceManager.GetString("namear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in English.
        /// </summary>
        public static string nameen {
            get {
                return ResourceManager.GetString("nameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name on Card.
        /// </summary>
        public static string nameoncard {
            get {
                return ResourceManager.GetString("nameoncard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Card ID Must be 14 digits.
        /// </summary>
        public static string nationalidcons {
            get {
                return ResourceManager.GetString("nationalidcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id Image.
        /// </summary>
        public static string NationalIdImagesImg {
            get {
                return ResourceManager.GetString("NationalIdImagesImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string orderdesc {
            get {
                return ResourceManager.GetString("orderdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Identifier.
        /// </summary>
        public static string orderid {
            get {
                return ResourceManager.GetString("orderid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Reference.
        /// </summary>
        public static string orderref {
            get {
                return ResourceManager.GetString("orderref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string orderum {
            get {
                return ResourceManager.GetString("orderum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Id.
        /// </summary>
        public static string passport {
            get {
                return ResourceManager.GetString("passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport ID Must be 14 digits.
        /// </summary>
        public static string passportcons {
            get {
                return ResourceManager.GetString("passportcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport image.
        /// </summary>
        public static string passportImg {
            get {
                return ResourceManager.GetString("passportImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 8 digits or more having one lower char and one upper char and one number.
        /// </summary>
        public static string passwordcons {
            get {
                return ResourceManager.GetString("passwordcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Link.
        /// </summary>
        public static string paylink {
            get {
                return ResourceManager.GetString("paylink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Lines.
        /// </summary>
        public static string phones {
            get {
                return ResourceManager.GetString("phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string postalcode {
            get {
                return ResourceManager.GetString("postalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price should be between 0 - 10000.
        /// </summary>
        public static string pricerange {
            get {
                return ResourceManager.GetString("pricerange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded Amount.
        /// </summary>
        public static string refamount {
            get {
                return ResourceManager.GetString("refamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string remember {
            get {
                return ResourceManager.GetString("remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Amount.
        /// </summary>
        public static string reqamount {
            get {
                return ResourceManager.GetString("reqamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is Required !.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string serialnum {
            get {
                return ResourceManager.GetString("serialnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string stdate {
            get {
                return ResourceManager.GetString("stdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string stname {
            get {
                return ResourceManager.GetString("stname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Percentage.
        /// </summary>
        public static string succgrade {
            get {
                return ResourceManager.GetString("succgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in Arabic.
        /// </summary>
        public static string titlear {
            get {
                return ResourceManager.GetString("titlear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in English.
        /// </summary>
        public static string titleen {
            get {
                return ResourceManager.GetString("titleen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Reference.
        /// </summary>
        public static string transref {
            get {
                return ResourceManager.GetString("transref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string university {
            get {
                return ResourceManager.GetString("university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Address.
        /// </summary>
        public static string workaddress {
            get {
                return ResourceManager.GetString("workaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Fax.
        /// </summary>
        public static string workfax {
            get {
                return ResourceManager.GetString("workfax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Leaving Date.
        /// </summary>
        public static string workleavedate {
            get {
                return ResourceManager.GetString("workleavedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Leaving Reasons.
        /// </summary>
        public static string workleavereasons {
            get {
                return ResourceManager.GetString("workleavereasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone.
        /// </summary>
        public static string workphone {
            get {
                return ResourceManager.GetString("workphone", resourceCulture);
            }
        }
    }
}
