//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventsNews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventsNews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESTA.Resources.EventsNews", typeof(EventsNews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic details is rquired.
        /// </summary>
        public static string DetailsArError {
            get {
                return ResourceManager.GetString("DetailsArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English details is reqiured.
        /// </summary>
        public static string DetailsEnError {
            get {
                return ResourceManager.GetString("DetailsEnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta Event.
        /// </summary>
        public static string EstaEvent {
            get {
                return ResourceManager.GetString("EstaEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date.
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Arabic Details.
        /// </summary>
        public static string EventDetailsAr {
            get {
                return ResourceManager.GetString("EventDetailsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event English Details.
        /// </summary>
        public static string EventDetailsEn {
            get {
                return ResourceManager.GetString("EventDetailsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Arabic Title.
        /// </summary>
        public static string EventTitleAr {
            get {
                return ResourceManager.GetString("EventTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event English Title.
        /// </summary>
        public static string EventTitleEn {
            get {
                return ResourceManager.GetString("EventTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events or news field is required.
        /// </summary>
        public static string FlagError {
            get {
                return ResourceManager.GetString("FlagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop a file or click to add Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is reqiured.
        /// </summary>
        public static string ImgError {
            get {
                return ResourceManager.GetString("ImgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp; Events.
        /// </summary>
        public static string News_Events {
            get {
                return ResourceManager.GetString("News&Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this an Event or News?.
        /// </summary>
        public static string NewsOrEvent {
            get {
                return ResourceManager.GetString("NewsOrEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string readMore {
            get {
                return ResourceManager.GetString("readMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Event.
        /// </summary>
        public static string SocialEvent {
            get {
                return ResourceManager.GetString("SocialEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Tuned!!.
        /// </summary>
        public static string StayTuned__ {
            get {
                return ResourceManager.GetString("StayTuned!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic title is required.
        /// </summary>
        public static string TitleArError {
            get {
                return ResourceManager.GetString("TitleArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English title is required.
        /// </summary>
        public static string TitleEnError {
            get {
                return ResourceManager.GetString("TitleEnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string viewMore {
            get {
                return ResourceManager.GetString("viewMore", resourceCulture);
            }
        }
    }
}
