//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESTA.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Contact.
        /// </summary>
        public static string addcontact {
            get {
                return ResourceManager.GetString("addcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Director.
        /// </summary>
        public static string adddirector {
            get {
                return ResourceManager.GetString("adddirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Current User.
        /// </summary>
        public static string addexitingmoderator {
            get {
                return ResourceManager.GetString("addexitingmoderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Upload Image.
        /// </summary>
        public static string addimage {
            get {
                return ResourceManager.GetString("addimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Moderator.
        /// </summary>
        public static string addmoderator {
            get {
                return ResourceManager.GetString("addmoderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Course.
        /// </summary>
        public static string addnewcourse {
            get {
                return ResourceManager.GetString("addnewcourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Info.
        /// </summary>
        public static string addressinfo {
            get {
                return ResourceManager.GetString("addressinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Users To This Course.
        /// </summary>
        public static string addusertocourse {
            get {
                return ResourceManager.GetString("addusertocourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with Terms and conditions, privacy, refund and cancellation policy.
        /// </summary>
        public static string agreepolicy {
            get {
                return ResourceManager.GetString("agreepolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Members.
        /// </summary>
        public static string allmem {
            get {
                return ResourceManager.GetString("allmem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Grade.
        /// </summary>
        public static string assigngrade {
            get {
                return ResourceManager.GetString("assigngrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assiging Prerequisites  For Course.
        /// </summary>
        public static string assignpre {
            get {
                return ResourceManager.GetString("assignpre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Date.
        /// </summary>
        public static string bandate {
            get {
                return ResourceManager.GetString("bandate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned users.
        /// </summary>
        public static string BannedUsers {
            get {
                return ResourceManager.GetString("BannedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Reasons.
        /// </summary>
        public static string banresons {
            get {
                return ResourceManager.GetString("banresons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a Member.
        /// </summary>
        public static string becamemember {
            get {
                return ResourceManager.GetString("becamemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits of Membership.
        /// </summary>
        public static string benefits {
            get {
                return ResourceManager.GetString("benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Of Directors.
        /// </summary>
        public static string board {
            get {
                return ResourceManager.GetString("board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string callus {
            get {
                return ResourceManager.GetString("callus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Register in this course.
        /// </summary>
        public static string cannotenroll {
            get {
                return ResourceManager.GetString("cannotenroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CETA.
        /// </summary>
        public static string ceta {
            get {
                return ResourceManager.GetString("ceta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CETA Courses.
        /// </summary>
        public static string cetacourses {
            get {
                return ResourceManager.GetString("cetacourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified Members.
        /// </summary>
        public static string cetaholders {
            get {
                return ResourceManager.GetString("cetaholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Egyptian Society of Technical Analysts (ESTA) provides its professional program of Technical Analysis which is currently acknowledged by the International Federation of Technical Analysts (IFTA). The course name is CETA which is an abbreviation for Certified ESTA Technical Analyst.
        ///
        ///        CETA is the third certificate around the world after Japan &amp; Australia&apos;s certificates that is accredited to be equivalent to the international Certificate of the international Federation of Technical Analysts (CFTe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cetaprogram {
            get {
                return ResourceManager.GetString("cetaprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string changepassheader {
            get {
                return ResourceManager.GetString("changepassheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of professional Ethics.
        /// </summary>
        public static string codeofethics {
            get {
                return ResourceManager.GetString("codeofethics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string confirmemail {
            get {
                return ResourceManager.GetString("confirmemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Copyright ESTA All Rights Reserved..
        /// </summary>
        public static string copyrights {
            get {
                return ResourceManager.GetString("copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number of Applicants is Complete.
        /// </summary>
        public static string coursecomplete {
            get {
                return ResourceManager.GetString("coursecomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Payment Confirmation.
        /// </summary>
        public static string courseconfirm {
            get {
                return ResourceManager.GetString("courseconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Details.
        /// </summary>
        public static string coursedetails {
            get {
                return ResourceManager.GetString("coursedetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string coursegrade {
            get {
                return ResourceManager.GetString("coursegrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Attendence only.
        /// </summary>
        public static string coursehint {
            get {
                return ResourceManager.GetString("coursehint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Level.
        /// </summary>
        public static string courselevel {
            get {
                return ResourceManager.GetString("courselevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Title.
        /// </summary>
        public static string coursename {
            get {
                return ResourceManager.GetString("coursename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Going to Enroll To This Course .Would You Like To Enroll &amp; Pay Now Or Pay Later?.
        /// </summary>
        public static string coursepopup {
            get {
                return ResourceManager.GetString("coursepopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string courses {
            get {
                return ResourceManager.GetString("courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses Orders.
        /// </summary>
        public static string coursesorders {
            get {
                return ResourceManager.GetString("coursesorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses Payments.
        /// </summary>
        public static string coursespayments {
            get {
                return ResourceManager.GetString("coursespayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Prerequisite.
        /// </summary>
        public static string cpre {
            get {
                return ResourceManager.GetString("cpre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Admin.
        /// </summary>
        public static string createadmin {
            get {
                return ResourceManager.GetString("createadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string currentpassword {
            get {
                return ResourceManager.GetString("currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User From Course.
        /// </summary>
        public static string deleteusercr {
            get {
                return ResourceManager.GetString("deleteusercr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in Arabic.
        /// </summary>
        public static string descar {
            get {
                return ResourceManager.GetString("descar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in English.
        /// </summary>
        public static string descen {
            get {
                return ResourceManager.GetString("descen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapprove.
        /// </summary>
        public static string disapprove {
            get {
                return ResourceManager.GetString("disapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Discussion Board.
        /// </summary>
        public static string discussionbf {
            get {
                return ResourceManager.GetString("discussionbf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Level.
        /// </summary>
        public static string editlevel {
            get {
                return ResourceManager.GetString("editlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string edu {
            get {
                return ResourceManager.GetString("edu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Info.
        /// </summary>
        public static string eduinfo {
            get {
                return ResourceManager.GetString("eduinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm you Email.
        /// </summary>
        public static string emailconfirm {
            get {
                return ResourceManager.GetString("emailconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Have Emailed you with your activation link ,please confirm your Email!.
        /// </summary>
        public static string emailconfirmdesc {
            get {
                return ResourceManager.GetString("emailconfirmdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        public static string emailus {
            get {
                return ResourceManager.GetString("emailus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke.
        /// </summary>
        public static string endMem {
            get {
                return ResourceManager.GetString("endMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends In .
        /// </summary>
        public static string endsin {
            get {
                return ResourceManager.GetString("endsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Date.
        /// </summary>
        public static string enrolldate {
            get {
                return ResourceManager.GetString("enrolldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled.
        /// </summary>
        public static string enrolled {
            get {
                return ResourceManager.GetString("enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled Users.
        /// </summary>
        public static string enrolledusers {
            get {
                return ResourceManager.GetString("enrolledusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian Society of Technical Analysts.
        /// </summary>
        public static string esta {
            get {
                return ResourceManager.GetString("esta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethics.
        /// </summary>
        public static string ethics {
            get {
                return ResourceManager.GetString("ethics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string eventdate {
            get {
                return ResourceManager.GetString("eventdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events &amp; News.
        /// </summary>
        public static string events_news {
            get {
                return ResourceManager.GetString("events&news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Title.
        /// </summary>
        public static string eventtitle {
            get {
                return ResourceManager.GetString("eventtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        public static string eventtype {
            get {
                return ResourceManager.GetString("eventtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string excellent {
            get {
                return ResourceManager.GetString("excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string exportToExcel {
            get {
                return ResourceManager.GetString("exportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILURE.
        /// </summary>
        public static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string followus {
            get {
                return ResourceManager.GetString("followus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ti-angle-double-right.
        /// </summary>
        public static string footerIco {
            get {
                return ResourceManager.GetString("footerIco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Members.
        /// </summary>
        public static string forignmem {
            get {
                return ResourceManager.GetString("forignmem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Dashboard.
        /// </summary>
        public static string forumdash {
            get {
                return ResourceManager.GetString("forumdash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string forums {
            get {
                return ResourceManager.GetString("forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Title.
        /// </summary>
        public static string forumtitle {
            get {
                return ResourceManager.GetString("forumtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string free {
            get {
                return ResourceManager.GetString("free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string good {
            get {
                return ResourceManager.GetString("good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already enrolled this course.
        /// </summary>
        public static string haveenrolled {
            get {
                return ResourceManager.GetString("haveenrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve Read Everything Carefully and I Accept.
        /// </summary>
        public static string haveread {
            get {
                return ResourceManager.GetString("haveread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Help?.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Front And Back Copy of Your ID Card.
        /// </summary>
        public static string IdCardLimit {
            get {
                return ResourceManager.GetString("IdCardLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFTA.
        /// </summary>
        public static string ifta {
            get {
                return ResourceManager.GetString("ifta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Upload Image.
        /// </summary>
        public static string imgclick {
            get {
                return ResourceManager.GetString("imgclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string inter {
            get {
                return ResourceManager.GetString("inter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Prerequisite Course ?.
        /// </summary>
        public static string ispre {
            get {
                return ResourceManager.GetString("ispre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job in Arabic.
        /// </summary>
        public static string jobar {
            get {
                return ResourceManager.GetString("jobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job in English.
        /// </summary>
        public static string joben {
            get {
                return ResourceManager.GetString("joben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Now.
        /// </summary>
        public static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        public static string lastupdatedate {
            get {
                return ResourceManager.GetString("lastupdatedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string levels {
            get {
                return ResourceManager.GetString("levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Members.
        /// </summary>
        public static string localmem {
            get {
                return ResourceManager.GetString("localmem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as CETA Holder.
        /// </summary>
        public static string markascert {
            get {
                return ResourceManager.GetString("markascert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Paid.
        /// </summary>
        public static string markpaid {
            get {
                return ResourceManager.GetString("markpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of people who can apply.
        /// </summary>
        public static string maxcoursemembers {
            get {
                return ResourceManager.GetString("maxcoursemembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string membership {
            get {
                return ResourceManager.GetString("membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mempership should be Paid first to Apply for a Course.
        /// </summary>
        public static string memnotpaid {
            get {
                return ResourceManager.GetString("memnotpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memperships Orders.
        /// </summary>
        public static string memorders {
            get {
                return ResourceManager.GetString("memorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mempership Is Paid.
        /// </summary>
        public static string mempaid {
            get {
                return ResourceManager.GetString("mempaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memperships Payments.
        /// </summary>
        public static string mempayments {
            get {
                return ResourceManager.GetString("mempayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIST.
        /// </summary>
        public static string mist {
            get {
                return ResourceManager.GetString("mist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        public static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator Name.
        /// </summary>
        public static string moderatorname {
            get {
                return ResourceManager.GetString("moderatorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderators.
        /// </summary>
        public static string moderators {
            get {
                return ResourceManager.GetString("moderators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with visa, Master Card, Meeza.
        /// </summary>
        public static string movetopay {
            get {
                return ResourceManager.GetString("movetopay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Courses.
        /// </summary>
        public static string mycourses {
            get {
                return ResourceManager.GetString("mycourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in Arabic.
        /// </summary>
        public static string namear {
            get {
                return ResourceManager.GetString("namear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in English.
        /// </summary>
        public static string nameen {
            get {
                return ResourceManager.GetString("nameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Event.
        /// </summary>
        public static string newevent {
            get {
                return ResourceManager.GetString("newevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Forum.
        /// </summary>
        public static string newforum {
            get {
                return ResourceManager.GetString("newforum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Level.
        /// </summary>
        public static string newlevel {
            get {
                return ResourceManager.GetString("newlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Members.
        /// </summary>
        public static string newmem {
            get {
                return ResourceManager.GetString("newmem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non of Them.
        /// </summary>
        public static string non {
            get {
                return ResourceManager.GetString("non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enrolled.
        /// </summary>
        public static string notenrolled {
            get {
                return ResourceManager.GetString("notenrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data to display.
        /// </summary>
        public static string notfound {
            get {
                return ResourceManager.GetString("notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Members.
        /// </summary>
        public static string oldmem {
            get {
                return ResourceManager.GetString("oldmem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Identifier.
        /// </summary>
        public static string orderid {
            get {
                return ResourceManager.GetString("orderid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Code.
        /// </summary>
        public static string ordernumber {
            get {
                return ResourceManager.GetString("ordernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Courses.
        /// </summary>
        public static string othercourses {
            get {
                return ResourceManager.GetString("othercourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Location.
        /// </summary>
        public static string ourlocation {
            get {
                return ResourceManager.GetString("ourlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string ourmission {
            get {
                return ResourceManager.GetString("ourmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Vission.
        /// </summary>
        public static string ourvission {
            get {
                return ResourceManager.GetString("ourvission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages Count.
        /// </summary>
        public static string pagesc {
            get {
                return ResourceManager.GetString("pagesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: password must be at least 8 characters including one uppercase,lowercase letter, one special character and alphanumeric characters.
        /// </summary>
        public static string passNote {
            get {
                return ResourceManager.GetString("passNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;- Membership fees cannot be refunded (membership renewal is in &lt;u&gt;July every year&lt;/u&gt;)&lt;br /&gt;
        /// &lt;br /&gt;
        ///&lt;strong&gt; Course Refund &amp; Cancellation Policy:&lt;/strong&gt;&lt;br /&gt;
        ///- Full Refund: 100% refund if canceled more than 7 days before the course begins.&lt;br /&gt;
        ///- Partial Refund: 80% refund for cancellations before &lt;u style=&quot;border-bottom: 1px dotted #000;
        ///    text-decoration: none;&quot;&gt;7 days&lt;/u&gt; from the beginning of the course.&lt;br /&gt;
        ///- No Refund will be accepted the day of starting the course.&lt;br /&gt;
        ///- No-Show  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string payinfo {
            get {
                return ResourceManager.GetString("payinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Later.
        /// </summary>
        public static string paylater {
            get {
                return ResourceManager.GetString("paylater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Mempership.
        /// </summary>
        public static string paymem {
            get {
                return ResourceManager.GetString("paymem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with Visa-Master Card-Meeza.
        /// </summary>
        public static string paynow {
            get {
                return ResourceManager.GetString("paynow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Online.
        /// </summary>
        public static string paynow2 {
            get {
                return ResourceManager.GetString("paynow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment State.
        /// </summary>
        public static string paystate {
            get {
                return ResourceManager.GetString("paystate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string pending {
            get {
                return ResourceManager.GetString("pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string personalinfo {
            get {
                return ResourceManager.GetString("personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By.
        /// </summary>
        public static string powerdby {
            get {
                return ResourceManager.GetString("powerdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string pp {
            get {
                return ResourceManager.GetString("pp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not register in this course without passing its prerequisites.
        /// </summary>
        public static string preinc {
            get {
                return ResourceManager.GetString("preinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites.
        /// </summary>
        public static string prereq {
            get {
                return ResourceManager.GetString("prereq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string prev {
            get {
                return ResourceManager.GetString("prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string quicklinks {
            get {
                return ResourceManager.GetString("quicklinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string readmore {
            get {
                return ResourceManager.GetString("readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string receipt {
            get {
                return ResourceManager.GetString("receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string refund {
            get {
                return ResourceManager.GetString("refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund &amp; Cancellation Policy.
        /// </summary>
        public static string refundpolicy {
            get {
                return ResourceManager.GetString("refundpolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registred Courses.
        /// </summary>
        public static string regCourses {
            get {
                return ResourceManager.GetString("regCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string regdate {
            get {
                return ResourceManager.GetString("regdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Email.
        /// </summary>
        public static string rejectemail {
            get {
                return ResourceManager.GetString("rejectemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string remember {
            get {
                return ResourceManager.GetString("remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string resetheader {
            get {
                return ResourceManager.GetString("resetheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string resetpassword {
            get {
                return ResourceManager.GetString("resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke Payment.
        /// </summary>
        public static string revokepaid {
            get {
                return ResourceManager.GetString("revokepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string searchresults {
            get {
                return ResourceManager.GetString("searchresults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Level ......
        /// </summary>
        public static string selectlevel {
            get {
                return ResourceManager.GetString("selectlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Us A Message.
        /// </summary>
        public static string sendusmessage {
            get {
                return ResourceManager.GetString("sendusmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member&apos;s Login.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string stdate {
            get {
                return ResourceManager.GetString("stdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Analysis.
        /// </summary>
        public static string ta {
            get {
                return ResourceManager.GetString("ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms&amp;Conditions.
        /// </summary>
        public static string termsCon {
            get {
                return ResourceManager.GetString("termsCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in English.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in Arabic.
        /// </summary>
        public static string titlear {
            get {
                return ResourceManager.GetString("titlear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unban.
        /// </summary>
        public static string unban {
            get {
                return ResourceManager.GetString("unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Courses.
        /// </summary>
        public static string upcourses {
            get {
                return ResourceManager.GetString("upcourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your updates have been commited successfully.
        /// </summary>
        public static string updatesSuccess {
            get {
                return ResourceManager.GetString("updatesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string uremail {
            get {
                return ResourceManager.GetString("uremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massage.
        /// </summary>
        public static string urmsg {
            get {
                return ResourceManager.GetString("urmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string urname {
            get {
                return ResourceManager.GetString("urname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string usersmanagement {
            get {
                return ResourceManager.GetString("usersmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string vgood {
            get {
                return ResourceManager.GetString("vgood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ESTA.
        /// </summary>
        public static string wel {
            get {
                return ResourceManager.GetString("wel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Home for All Technicians.
        /// </summary>
        public static string wel2 {
            get {
                return ResourceManager.GetString("wel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilization will not be without Education.
        /// </summary>
        public static string wel2desc {
            get {
                return ResourceManager.GetString("wel2desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Esta Now.
        /// </summary>
        public static string wel3 {
            get {
                return ResourceManager.GetString("wel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was created since 2000.
        /// </summary>
        public static string wel3desc {
            get {
                return ResourceManager.GetString("wel3desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTA is welcoming  &lt;br&gt;any new volunteers.
        /// </summary>
        public static string wel4 {
            get {
                return ResourceManager.GetString("wel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New volunteers are our main power.
        /// </summary>
        public static string wel4desc {
            get {
                return ResourceManager.GetString("wel4desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Choose Us?.
        /// </summary>
        public static string whyus {
            get {
                return ResourceManager.GetString("whyus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Info.
        /// </summary>
        public static string workinfo {
            get {
                return ResourceManager.GetString("workinfo", resourceCulture);
            }
        }
    }
}
